[package]
name = "itaiji-rust"
version = "0.1.0"
authors = ["camelmasa <camelmasa@gmail.com>"]
edition = "2018"

[dependencies]
yaml-rust = "0.4"
libc = "0.2.60"
lazy_static = "1.3.0"

[lib]
name = "itaiji"
crate-type = ["dylib"]
